#!/usr/bin/env python3
"""Embeds a SPIR-V binary as a C++ byte array header.

Used by the CMake avbd_compile_slang() function (see CMakeLists.txt, the
AVBD_VULKAN block) to turn src/**/shaders/*.slang -> *.spv -> a generated header
that the Vulkan backend consumes without a runtime file load. Mirrors what a
resource-embedding step does for any other GPU kernel format; there is nothing
Vulkan-specific about the script itself.

Usage: embed_spirv.py <input.spv> <output.h> <symbol_name>
"""
import sys


def main():
    if len(sys.argv) != 4:
        print("usage: embed_spirv.py <input.spv> <output.h> <symbol_name>", file=sys.stderr)
        return 1
    src, dst, symbol = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(src, "rb") as f:
        data = f.read()
    if len(data) % 4 != 0:
        print(f"error: {src} is not a multiple of 4 bytes ({len(data)})", file=sys.stderr)
        return 1

    words = len(data) // 4
    with open(dst, "w", newline="\n") as out:
        out.write("// Generated by tools/embed_spirv.py -- do not edit.\n")
        out.write("#pragma once\n")
        out.write("#include <cstdint>\n\n")
        out.write(f"inline const uint32_t {symbol}[] = {{\n")
        for i in range(words):
            word = int.from_bytes(data[i * 4:i * 4 + 4], "little")
            out.write(f"0x{word:08x},")
            if (i + 1) % 8 == 0:
                out.write("\n")
        out.write("\n};\n")
        out.write(f"inline const size_t {symbol}_words = {words};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
