/*
 * Copyright (c) 2026 Chris Giles
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies.
 * Chris Giles makes no representations about the suitability
 * of this software for any purpose.
 * It is provided "as is" without express or implied warranty.
 */

#pragma once

// Compute pipeline loading from embedded SPIR-V byte arrays, sharing ONE pipeline
// layout across every kernel: a single 8-byte push-constant range (the argument
// struct's device address). No descriptor sets
// at all, since every buffer is addressed through buffer device address pointers.

#include "vk_device.h"

#include <cstdint>
#include <string>

namespace avbdvk
{

// One pipeline layout for the whole engine: push_constant(uint64 argsAddr), no
// descriptor sets. Created once, shared by every Pipeline below.
class PipelineLayout
{
public:
    void init(Device &dev);
    void destroy();
    VkPipelineLayout handle() const { return m_layout; }

private:
    Device *m_dev = nullptr;
    VkPipelineLayout m_layout = VK_NULL_HANDLE;
};

class Pipeline
{
public:
    // spirv/spirvWords: the embedded byte array and its length in 32-bit words
    // (as generated by the CMake embed step -- see cmake/EmbedShader.cmake).
    void init(Device &dev, PipelineLayout &layout, const uint32_t *spirv, size_t spirvWords,
              const char *entryPoint, const char *debugName = nullptr);
    void destroy();

    VkPipeline handle() const { return m_pipeline; }
    VkPipelineLayout layout() const { return m_layout; }
    // debugName if given, else the entry point. Used as the per-kernel profiler label.
    const char *name() const { return m_name.c_str(); }

private:
    std::string m_name;
    Device *m_dev = nullptr;
    VkPipeline m_pipeline = VK_NULL_HANDLE;
    VkShaderModule m_module = VK_NULL_HANDLE;
    VkPipelineLayout m_layout = VK_NULL_HANDLE;
};

} // namespace avbdvk
